apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-dashboard
  namespace: capi-system
  labels:
    app: capi-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capi-dashboard
  template:
    metadata:
      labels:
        app: capi-dashboard
    spec:
      serviceAccountName: capi-dashboard
      containers:
        - name: dashboard
          image: vcr.infiniband.vn/thalt-test/capi-dash:v16
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
            initialDelaySeconds: 8
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
      imagePullSecrets:
        - name: registry-auth
---
apiVersion: v1
kind: Service
metadata:
  name: capi-dashboard
  namespace: capi-system
spec:
  selector:
    app: capi-dashboard
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30000
